version: "3"

services:
  mqtt-to-prom:
    image: mqtt-to-prom
    ports:
      - 1323:1323
    restart: unless-stopped
    depends_on:
      - mosquitto
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./mqtt/:/mosquitto/:rw
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    volumes:
      - ./prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090

volumes:
  prometheus_data: {}