version: "3"

services:
  mqtt-to-prom:
    image: mqtt-to-prom
    ports:
      - 1323:1323
    restart: always
    depends_on:
      - mosquitto
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./mqtt/:/mosquitto/:rw
    ports:
      - 1883:1883
      - 9001:9001
    restart: always
